name: "Terraform CI/CD Pipeline"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        type: choice
        options:
          - apply
          - destroy

env:
  TF_DIR: ./Terraform
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}

jobs:
  terraform_validate:
    name: "Validate & Plan"
    runs-on: ubuntu-latest
    # Always run validate first for both apply and destroy
    if: ${{ github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_DIR }}

      - name: Conditional Plan
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform plan -var-file="default.tfvars"
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform plan -destroy -var-file="default.tfvars"
          if
        working-directory: ${{ env.TF_DIR }}

  terraform_apply:
    name: "Terraform Apply"
    needs: terraform_validate
    runs-on: ubuntu-latest
    # Only run when apply is selected
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="default.tfvars"
        working-directory: ${{ env.TF_DIR }}

  terraform_destroy:
    name: "Terraform Destroy"
    needs: terraform_validate
    runs-on: ubuntu-latest
    # Only run when destroy is selected
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="default.tfvars"
        working-directory: ${{ env.TF_DIR }}

        #git 
