name: "Terraform "

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        type: choice
        options:
          - apply
          - destroy

env:
  TF_DIR: ./Terraform
  ACTION: ${{ github.event.inputs.action || 'apply' }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}

jobs:
  terraform_validate:
    name: "Validate & Plan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_DIR }}

      # - name: Conditional Plan
      #   run: |
      #     if [ "${{ env.ACTION }}" == "apply" ]; then
      #       terraform plan -out=tfplan -var-file="default.tfvars"
      #     elif [ "${{ env.ACTION }}" == "destroy" ]; then
      #       terraform plan -destroy -out=tfplan -var-file="default.tfvars"
      #     fi
      #   working-directory: ${{ env.TF_DIR }}

  terraform_apply:
    name: "Terraform Apply"
    needs: terraform_validate
    runs-on: ubuntu-latest
    # if: env.ACTION == 'apply'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="default.tfvars"
        working-directory: ${{ env.TF_DIR }}

  terraform_destroy:
    name: "Terraform Destroy"
    needs: terraform_validate
    runs-on: ubuntu-latest
    # if: env.ACTION == 'destroy'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="default.tfvars"
        working-directory: ${{ env.TF_DIR }}
