name: "Terraform Manual Trigger Test"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform Action (apply/destroy)"
        required: true
        type: choice
        options:
          - apply
          - destroy

env:
  TF_DIR: ./Terraform
  TF_VERSION: 1.5.7
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}

jobs:
  show_input:
    name: "Print Selected Action"
    runs-on: ubuntu-latest
    steps:
      - name: Show the selected action
        run: echo "Selected action is: ${{ github.event.inputs.action }}"

  terraform_apply:
    name: "Apply Infrastructure"
    if: ${{ github.event.inputs.action == 'apply' }}
    runs-on: ubuntu-latest
    steps:
      - name: Apply Step
        run: echo "Running Terraform APPLY"

  terraform_destroy:
    name: "Destroy Infrastructure"
    if: ${{ github.event.inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Destroy Step
        run: echo "Running Terraform DESTROY"
