name: "Terraform CI/CD Pipeline"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        type: choice
        options:
          - apply
          - destroy

env:
  TF_DIR: ./Terraform
  TF_VERSION: 1.5.7
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}

jobs:
  terraform_apply:
    name: "Terraform Apply"
    if: ${{ github.event.inputs.action == 'apply' }}
    runs-on: ubuntu-latest

    steps:
      - name: 🧪 Debug Input
        run: echo "🎯 Action: ${{ github.event.inputs.action }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Apply
        run: terraform apply -auto-approve -var-file="default.tfvars"
        working-directory: ${{ env.TF_DIR }}

  terraform_destroy:
    name: "Terraform Destroy"
    if: ${{ github.event.inputs.action == 'destroy' }}
    runs-on: ubuntu-latest

    steps:
      - name: 🧪 Debug Input
        run: echo "🎯 Action: ${{ github.event.inputs.action }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Destroy
        run: terraform destroy -auto-approve -var-file="default.tfvars"
        working-directory: ${{ env.TF_DIR }}
