name: "Terraform CI/CD Pipeline"

on:
  push:
    branches: [dev]
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action (apply/destroy)'
        required: true
        type: choice
        options: [apply, destroy]

env:
  TF_DIR: ./Terraform  # Terraform directory path
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}

jobs:
  terraform_validate:
    name: "Validate & Plan"
    runs-on: ubuntu-latest
    environment: production
    # Run on push OR if workflow_dispatch is triggered with apply/destroy
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.action == 'apply' || github.event.inputs.action == 'destroy'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Plan
        run: |
          if [ "${{ github.event.inputs.action || 'plan' }}" == "destroy" ]; then
            terraform plan -destroy -var-file="default.tfvars"
          else
            terraform plan -var-file="default.tfvars"
          fi
        working-directory: ${{ env.TF_DIR }}

  terraform_apply:
    name: "Apply Changes"
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' }}
    runs-on: ubuntu-latest
    environment: production
    needs: [terraform_validate]  # Validate must complete first

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="default.tfvars"
        working-directory: ${{ env.TF_DIR }}

  terraform_destroy:
    name: "Destroy Infrastructure"
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    environment: production
    needs: [terraform_validate]  # Validate must complete first

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="default.tfvars"
        working-directory: ${{ env.TF_DIR }}