name: "Terraform CI/CD Pipeline"

on:
  push:
    branches: [dev]
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action (apply/destroy)'
        required: true
        type: choice
        options: [apply, destroy]

env:
  TF_DIR: ./Terraform
  AWS_REGION: us-east-1

jobs:
  terraform_validate:
    name: "Validate & Plan"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="key=terraform.tfstate"
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Plan
        run: terraform plan -var-file="default.tfvars" -out=tfplan
        working-directory: ${{ env.TF_DIR }}
        
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ${{ env.TF_DIR }}/tfplan

  terraform_apply:
    name: "Apply Changes"
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' }}
    runs-on: ubuntu-latest
    environment: production
    needs: terraform_validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ${{ env.TF_DIR }}

      - name: Terraform Apply
        run: terraform apply tfplan
        working-directory: ${{ env.TF_DIR }}

  terraform_destroy:
    name: "Destroy Infrastructure"
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    environment: production
    needs: terraform_validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="key=terraform.tfstate"
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="default.tfvars"
        working-directory: ${{ env.TF_DIR }}